### PR TITLE
Widgetize

### PR DESCRIPTION
**Pull request by nshafer**
Hi Nar, Chhantyal,

I like your module, and I really like selectize.js, and will be using it in a new project. I thought that using a custom widget instead of modifying django templates would make for an easier install and integration. I also needed to updated it for Django 1.9, so I thought I'd go ahead and make a few changes while I was in there. I also made sure it works with Python 2.7 and 3.4. I'm developing with 3.4, but a lot are still on 2.7. Anyways, here are my tweaks.

Thanks,
Nate

### CODE REVIEW

**Comment by nshafer** [comment]
Oh, this should also resolve issue #1.

**Comment by chhantyal** [comment]
Oh that's very good idea. Thank you.

I am still stuck with bit older version of django, but I will test/review it in next couple of days. :+1:

**Comment by nshafer** [comment]
Of course =)

I think it would probably work with older versions of Django, but I haven't tested. I normally just target current supported releases =)

**Comment by chhantyal** [comment]
Hi @nshafer 
I released a version with this PR https://github.com/chhantyal/taggit-selectize/pull/4

This adds 1.9 compatibility without other changes. I plan to release another version with your changes. Could you your PR?

Thanks

**Comment by nshafer** [comment]
I have merged your changes in to my PR, so it's ready for merging again. Let me know if you see any problems and I'll take care of them.

**Comment by chhantyal** [comment]
Thank you. Will bump version to 2.0 with your changes.

**Comment by nshafer** [comment]
No problem, thanks for the module =)

**Pull request merged**
