### PR TITLE
BUGFIX: extra hash # symbol deleted

### PR DESCRIPTION
**Pull request by mordaha**

### CODE REVIEW

**Comment by chhantyal** [comment]
Could you please write a bit what was bug?

**Comment by chhantyal** [comment]
cc. @nshafer

**Comment by mordaha** [comment]
https://developer.mozilla.org/en/docs/Web/CSS/Attribute_selectors
[attr=value]
Represents an element with an attribute name of attr and whose value is exactly "value".

'#' is not part of attribute 'id' value when id selected like attribute

$('#id_tags') or $['[id=id_tags]']

**Comment by mordaha** [comment]
Ah :) the bug was that jquery selects nothing with that selector and nothing happens with input field

**Comment by nshafer** [comment]
So this was changed from `$("#%(id)s").selectize()` to `$("input[id=#%(id)s]").selectize()` by pull request #8, which to be honest, confuses me. I haven't looked in to it until now, but I did test the previous code with multiple TaggableManager fields in the same model and it worked fine. Each field is going to have a distinct `id`, per how Django sets up the form, but also just due to the rules of HTML. So I don't understand what case would exist where there would be multiple input fields with the same ID, which is what the original PR purports?

So.. let's think through an example. Let's say there is a model like so (Have to use a custom through model to prevent clashes for Taggit)

```
class BlogOtherTags(TaggedItemBase):
    content_object = models.ForeignKey('Blog')

class Blog(models.Model):
    ...
    tags = TaggableManager()
    other_tags = TaggableManager(through=BlogOtherTags, related_name = "blog_other_tags")
```

A ModelForm will correctly generate a form that looks like this:

```
...
<input id="id_other_tags" name="other_tags" type="text" />
...
<input id="id_tags" name="tags" type="text" />
```

And thus, the TagSelectize widget, before PR #8, would generate two sections of JS, one which targets the first field with `$("#id_tags").selectize()` and another which targets the second field with `$("#id_other_tags").selectize()`, thus there's no conflict. Really, all that PR #8 does is change the jQuery selector from targeting any element with the given ID, and instead only targets elements of type `input` which the given ID prepended with '#'. So this patch does indeed fix the problem caused by PR #8, but what I'm getting at, is what is the case that I'm not seeing here that caused the original PR #8?

We need to write some tests for this module. =)

@ahoho can you clue me in on what I'm missing?

Thanks,
Nate

**Comment by mordaha** [comment]
``` javascript
$("#id_other_tags") == $("input[id=id_other_tags]")

$("input[id=#id_other_tags]") == <input id="#id_other_tags"> !=  <input id="id_other_tags">
```

**Comment by chhantyal** [comment]
Thanks @nshafer for explanation. 

Looks like you are using this package more than me, would you like to be added to project so that you could review & merge PRs (maintain the package)?

Some tests would really help. But sadly I don't have any time these days :(

**Comment by ahoho** [comment]
@nshafer , this was intended to fix the issue where there were multiple tag input forms on a page that all corresponded to the same field of a single model. In that case, one ends up with duplicate `<input>` ids. I now realize using formsets are the sanctioned way of handling multiple objects per page, and they automatically generate unique ids. With that in mind I think it makes sense to revert my PR. My apologies for the confusion.

As penance, I'll create a pull request with an example of how this can work on a user-facing site (as opposed to admin-only) if that would be helpful.

**Comment by nshafer** [comment]
No worries

@chhantyal: Sure, I can help admin

**Comment by chhantyal** [comment]
Great. I added you as collaborator. Feel free to review/merge.

**Comment by nshafer** [comment]
@chhantyal I have uploaded a new version with the fix. Can you `sdist` and `bdist_wheel` and upload the new version (2.2.0) to PyPI, please?

Thanks,
Nate

**Comment by chhantyal** [comment]
Done https://pypi.python.org/pypi/taggit-selectize/2.2.0

Thank you :+1:

**Pull request closed without merging**
