### PR TITLE
For compatibility

### PR DESCRIPTION
**Pull request by c4ys**

### CODE REVIEW

**Comment by chhantyal** [comment]
Hi, thank you for pull request.

I would prefer try/except pattern over version check.

```
try:
    from django.urls import reverse
except ImportError:
    from django.core.urlresolvers import reverse
```

I think this is pattern Django itself follows. Once you update the pull request, I am happy to merge and release new version.

**Comment by vdboor** [comment]
I've pushed a try..except version in pr #14

**Comment by chhantyal** [comment]
Thank you @c4ys and @vdboor 

I made a new release https://pypi.org/project/taggit-selectize/2.4.0/

`pip install taggit-selectize==2.4.0`

**Comment by vdboor** [comment]
Wonderful! I'm glad to see one more dependency fixed that blocked Django 2.0! 👍

**Pull request closed without merging**
